app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('faq/', views.faq_view, name='faq'),
    path("report/", views.report, name="report"),
    path("login/", views.login, name="login"),
    path("logout/", views.logOut, name="logOut"),
    path("signup/", views.signUp, name="signup"),
    path('reports/', views.report_list, name='report_list'),
    path("report_success/", views.report_success, name="report_success"),
    path("notifications/", views.notifications, name="notifications"),
    path('mark_review_in_progress/<int:report_id>/', views.mark_review_in_progress, name='mark_review_in_progress'),
    path('mark_review_completed/<int:report_id>/', views.mark_review_completed, name='mark_review_completed'),
    path('reports/<uuid:report_uuid>/',views.report_detail,name='report_detail'),
    path('delete_report/<uuid:report_uuid>/', views.delete_report, name='delete_report'),
]

falseAdvertisement/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.views import LogoutView



urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
    path('', include(('app.urls', 'app'), namespace='app')),
    re_path(r'^(?P<path>.*)/$', RedirectView.as_view(url='/')),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<style>body { padding-bottom: 60px;}</style>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>False Advertisement</title>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">False Advertisement</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNavAltMarkup"
                        aria-controls="navbarNavAltMarkup"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="{% url 'app:report' %}">Report</a>
                        {% if user.is_authenticated %}
                            {% if user.is_superuser and not user.is_staff %}
                            <a class="nav-link" href="{% url 'app:report_list' %}">Current Reports</a>
                            {% else %}
                            <a class="nav-link position-relative" href="{% url 'app:notifications' %}">Notifications
                            {% if status_change_count > 0 %}
                            <span class="badge">{{ status_change_count }}</span>
                            {% endif %}
                        </a>
                            <a class="nav-link" href="{% url 'app:report_list' %}">My Reports</a>
                            {% endif %}
                        <a class="nav-link" href="{% url 'app:logOut' %}">Logout</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'app:login' %}">Login</a>
                        <a class="nav-link" href="{% url 'app:signup' %}">Sign Up</a>
                        {% endif %}
                        <a class="nav-link" href="{% url 'app:faq' %}">FAQ</a>
                    </div>
                </div>
            </div>
        </nav>
    <div class="container">
            {% block content %}{% endblock %}
        </div>
    <footer class="bg-light text-center text-lg-start footer fixed-bottom">
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05)">
                Ans Shaukat, Milo Schwartz, Larissa Cybyk, Delia Curran, Ali Bohliga
            </div>
        </footer>
    </body>
</html>

templates/faq.html
{% extends 'base.html' %} {% block content %}

<style>
  .faq-header {
    background-color: #f7f7f7;
    margin-bottom: 10px;
    padding: 10px 15px;
    cursor: pointer;
  }
  .faq-content {
    padding: 0 15px 10px;
    display: none;
  }
</style>
<div class="container mt-5">
  <h2 class="mb-0">
    General Advice and Resources on Spotting False Advertising
  </h2>
  <div id="collapseAdvice">
    <div class="card-body">
      <p>
        Being able to spot false advertising is crucial to making informed
        decisions as a consumer. Here are some tips and resources that can help:
      </p>
      <ul>
        <li>
          <strong>Check for Exaggerated Claims:</strong> Be wary of phrases like
          "miracle cure" or "quick fix" that suggest unrealistic results.
        </li>
        <li>
          <strong>Verify with Trusted Sources:</strong> Look up product claims
          through reliable and independent sources such as government or
          educational websites.
        </li>
        <li>
          <strong>Understand the Fine Print:</strong> Always read the fine print
          in advertisements to understand what is really being offered.
        </li>
        <li>
          <strong>Be Skeptical of Limited Time Offers:</strong> Pressure to act
          quickly can be a tactic to prevent you from researching the veracity
          of a claim.
        </li>
      </ul>
      <p>
        For more detailed information and legal guidelines on advertising, you
        can visit the following links:
      </p>
      <ul>
        <li>
          <a
            href="https://www.ftc.gov/business-guidance/resources/advertising-faqs-guide-small-business"
            target="_blank"
            >FTC Guide for Small Businesses on Advertising</a
          >
        </li>
        <li>
          <a
            href="https://www.consumer.ftc.gov/articles/how-recognize-and-avoid-phishing-scams"
            target="_blank"
            >FTC Tips on How to Recognize and Avoid Phishing Scams</a
          >
        </li>
        <li>
          <a href="https://www.bbb.org/ad-truth/" target="_blank"
            >Better Business Bureau's Ad Truth Campaign</a
          >
        </li>
      </ul>
    </div>
  </div>
  <h2 class="mb-3">Frequently Asked Questions</h2>
  <div id="accordionExample">
    <div class="card mb-3">
      <div class="card-header faq-header" id="headingOne">
        <h2 class="mb-0">
          <button
            class="btn btn-link"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseOne"
          >
            What is False Advertisement App?
          </button>
        </h2>
      </div>
      <div
        id="collapseOne"
        class="collapse show"
        data-bs-parent="#accordionExample"
      >
        <div class="card-body">
          False Advertisement is a platform where users can report misleading
          ads. Users can choose to log in or report anonymously to help promote
          transparency and awareness about false advertising online.
        </div>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-header faq-header" id="headingTwo">
        <h2 class="mb-0">
          <button
            class="btn btn-link"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseTwo"
          >
            What are the benefits of registering and logging in?
          </button>
        </h2>
      </div>
      <div id="collapseTwo" class="collapse" data-bs-parent="#accordionExample">
        <div class="card-body">
          Registering and logging in allow you to save reports, revisit and
          manage them easily, and participate in our community by voting on
          reports. This helps identify the most pressing cases of false
          advertising.
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-header faq-header" id="headingThree">
        <h2 class="mb-0">
          <button
            class="btn btn-link"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseThree"
          >
            How can I report anonymously?
          </button>
        </h2>
      </div>
      <div
        id="collapseThree"
        class="collapse"
        data-bs-parent="#accordionExample"
      >
        <div class="card-body">
          You can choose not to log in and still submit reports. When reporting
          anonymously, your identity is not disclosed to other users or
          companies.
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-header faq-header" id="headingFour">
        <h2 class="mb-0">
          <button
            class="btn btn-link"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseFour"
          >
            How do I search for reports?
          </button>
        </h2>
      </div>
      <div
        id="collapseFour"
        class="collapse"
        data-bs-parent="#accordionExample"
      >
        <div class="card-body">
          Use the search bar on the homepage to filter reports by name or
          category, making it easier to find specific cases of false
          advertising.
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-header faq-header" id="headingFive">
        <h2 class="mb-0">
          <button
            class="btn btn-link"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseFive"
          >
            How are reports reviewed and managed?
          </button>
        </h2>
      </div>
      <div
        id="collapseFive"
        class="collapse"
        data-bs-parent="#accordionExample"
      >
        <div class="card-body">
          Admins review each report, add comments, and may update the report
          status. Users receive notifications about any actions taken on their
          submitted reports.
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-header faq-header" id="headingSix">
        <h2 class="mb-0">
          <button
            class="btn btn-link"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseSix"
          >
            How can I identify false advertising?
          </button>
        </h2>
      </div>
      <div id="collapseSix" class="collapse" data-bs-parent="#accordionExample">
        <div class="card-body">
          Identifying false advertising involves checking for exaggerated
          claims, misleading statements, or offers that seem too good to be
          true. It is important to verify such information with credible sources
          before accepting it as true.
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-header faq-header" id="headingSeven">
        <h2 class="mb-0">
          <button
            class="btn btn-link"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseSeven"
          >
            What happens after I submit a report?
          </button>
        </h2>
      </div>
      <div
        id="collapseSeven"
        class="collapse"
        data-bs-parent="#accordionExample"
      >
        <div class="card-body">
          After submitting a report, it will be reviewed by our admin team for
          validity and necessary action. You will receive notifications about
          the status of your report and any comments or actions taken.
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-header faq-header" id="headingEight">
        <h2 class="mb-0">
          <button
            class="btn btn-link"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseEight"
          >
            How can I share a report?
          </button>
        </h2>
      </div>
      <div
        id="collapseEight"
        class="collapse"
        data-bs-parent="#accordionExample"
      >
        <div class="card-body">
          Each report has a 'Share' button that allows you to easily share the
          report on various social media platforms or via email, helping to
          increase awareness and reach a larger audience. Once you click the
          'Share' button, the link to the report will be copied to your
          clipboard.
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-header faq-header" id="headingNine">
        <h2 class="mb-0">
          <button
            class="btn btn-link"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseNine"
          >
            How do admins manage reports?
          </button>
        </h2>
      </div>
      <div
        id="collapseNine"
        class="collapse"
        data-bs-parent="#accordionExample"
      >
        <div class="card-body">
          Admins review reports for adherence to guidelines, verify their
          content, and may engage with the reporting users. They play a crucial
          role in maintaining the integrity and accuracy of reports on the
          platform.
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-header faq-header" id="headingTen">
        <h2 class="mb-0">
          <button
            class="btn btn-link"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseTen"
          >
            What are the privacy policies regarding the information I share?
          </button>
        </h2>
      </div>
      <div id="collapseTen" class="collapse" data-bs-parent="#accordionExample">
        <div class="card-body">
          We prioritize your privacy. Information shared during reporting can be
          kept anonymous at your request. For registered users, personal
          information is securely stored and not disclosed to third parties
          without consent.
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  var acc = document.getElementsByClassName("faq-header");
  for (var i = 0; i < acc.length; i++) {
    acc[i].addEventListener("click", function () {
      var panel = this.nextElementSibling;
      panel.style.display = panel.style.display === "block" ? "none" : "block";
    });
  }
</script>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
    {% load socialaccount %}
    <div class="alert alert-danger" role="alert">
        DISCLAIMER: This is NOT a real app. Please DO NOT make any reports. This website is a project for CS 3240 at UVA.
    </div>
            {% if user.is_authenticated %}
                {% if user.is_superuser and not user.is_staff %}

                <h6><strong> Hello, {{user.username}} You are a site admin.</strong></h6>

                {% else %}

                <h6><strong>Hello, {{user.username}}.</strong></h6>

                {% endif %}
            {% else %}

                <h6><strong>Hello Anonymous User, You are not logged in.</strong></h6>
            {% endif %}
<div style="display: flex; justify-content: space-between;">
    <div style="text-align: left;">
        Welcome to our False Advertisement Whistleblower Application. This platform is designed
        for individuals who have experienced deceptive or misleading practices in advertising.
        Our mission is to provide a safe and
        secure environment where you can report such instances for public
        awareness and prevention.
        <br>
<br>
        In addition, this application serves as a resource for those who wish to stay informed about current misleading
        advertisements and avoid potential scams. We have a collection of reports submitted by users. Please note
        that certain private information in these reports has been redacted for privacy reasons.
<br>
<br>
        You have the option to search for specific companies or categories. Furthermore, if you find a report
        particularly helpful or noteworthy, you have the ability to ‘like’ or share it.
        <br>
<br>
        Thank you for choosing our application as your trusted source for reporting and staying informed about
        false
        advertisements.
        <br>
    </div>
    <img src="{% static 'images/Designer.png' %}" alt="Report False Ad" style="height: 320px; width: 330px;"
         class = "rounded float-start">
</div>
<div class="container my-3">
  <div class="row g-2">

    <div class="col">
      <form method="GET" action="{% url 'app:index' %}">
        <div class="input-group">
          <input type="text" name="company_name" value="{{ request.GET.company_name }}" placeholder="Search by company name..." class="form-control">
          <button type="submit" class="btn btn-outline-secondary">Search</button>
        </div>
      </form>
    </div>
    <div class="col">
    <form method="GET" action="{% url 'app:index' %}">
        <div class="input-group">
            <select name="category" class="form-control">
                <option value="">Search by category...</option>
                <option value="Food">Food</option>
                <option value="Retail">Retail</option>
                <option value="Jobs">Jobs</option>
                <option value="Services">Services</option>
                <option value="Medical">Medical</option>
                <option value="Other">Other</option>
            </select>
            <button type="submit" class="btn btn-outline-secondary">Search</button>
        </div>
    </form>
</div>
  </div>

 <div class="my-2">
    <a href="{{ toggle_sort_url }}" class="btn btn-info {% if sort_by_likes %}active{% endif %}">
        {% if sort_by_likes %}
            Sort by Newest
        {% else %}
            Sort by Likes
        {% endif %}
    </a>
</div>



<div class="container-scrollable">
  <h1 class="mb-3">Reports</h1>
  <ul class="list-group">
    {% for report in reports %}

    <li class="list-group-item" id="report-{{ report.id }}">
        <strong>Company Name:</strong> {{ report.company_name }}<br>
        <strong>Reason:</strong> {{ report.reason }}<br>
        <strong>Category:</strong> {{ report.category }}<br>
        <strong>Report Date:</strong> {{ report.report_date }}<br>
        <div class="mt-3 d-flex flex-row align-items-center justify-content-between">
            <div>
              <span>{{ report.likes_count }} Likes</span>
            <form method="POST">
              {% csrf_token %}
              <input type="hidden" name="report_id" value="{{ report.id }}">
              {% if user.is_authenticated %}
                  <form method="POST">
                    {% csrf_token %}
                    {% if report.user_liked %}
                    <button type="submit" name="unlike" class="btn btn-secondary">Unlike</button>
                    {% else %}
                    <button type="submit" name="like" class="btn btn-primary">Like</button>
                    {% endif %}
                  </form>
                {% else %}
                    <p><i>Please log in to like this report.</i></p>
                {% endif %}
            </form>
            </div>
                <div style="text-align: right;">
            <button onclick="copyToClipboard('{{ report.share_url }}')" class="btn btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share" viewBox="0 0 16 16">
                    <path d="M13.5 1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.5 2.5 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5m-8.5 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m11 5.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3"/>
                </svg>
            </button>
        </div>
    </li>
      </li>
    {% endfor %}
  </ul>
</div>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
function copyToClipboard(text) {
    var textarea = document.createElement("textarea");
    textarea.textContent = text;
    document.body.appendChild(textarea);
    textarea.select();
    try {
        document.execCommand("copy");
        swal("Link copied!", " ", "success");
    } catch (ex) {
        console.warn("Copy to clipboard failed.", ex);
        return false;
    } finally {
        document.body.removeChild(textarea);
    }
}
</script>
    <script>
window.onload = function() {
    var fragment = window.location.hash;
    if (fragment.startsWith('#report-')) {
        var reportElement = document.querySelector(fragment);

        if (reportElement) {
            reportElement.classList.add('highlight');
        }
    }
};
</script>
<style>
.highlight {
    background-color: yellow;
}
.list-group-item {
    word-wrap: break-word;
}
</style>
{% endblock %}

templates/notifications.html
{% extends 'base.html' %}
{% block content %}
{% load socialaccount %}
{% if user.is_authenticated %}
<div class="container">
  <h2>Notifications</h2>

  <ul class="list-group">
    {% for notification in notifications %}
    <li class="list-group-item">
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <strong><p>{{ notification.message }}</p></strong>
        </div>
        <div>
            <span class="badge {% if notification.report.status == 'Review-Pending' %} bg-warning {% elif notification.report.status == 'Review-In-Progress' %} bg-info {% else %} bg-success {% endif %}">
              {{ notification.report.status }}
            </span>
        </div> 
      </div>
      <div class="container">  
        <p>{{ notification.timestamp }}</p>
        <p>Company Name: {{ notification.report.company_name }}</p>
        Report Details:  
        <a href="{% url 'app:report_detail' notification.report.report_uuid %}">{{ notification.report.reason }}</a>
      </div>
    </li>
    {% endfor %}
  </ul>
  
</div>
{% else %}
<p>
You are not logged in. Please login to view notifications about your current reports.
<p>
 {% endif %}
{% endblock %}

templates/report_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h2>Report Details</h2>

  <div class="my-3">
      <p><strong>Likes:</strong> {{ report.likes_count }}</p>

      {% if user.is_authenticated %}
      <form method="POST">
          {% csrf_token %}
          {% if user_liked %}
          <button type="submit" name="unlike" class="btn btn-secondary">Unlike</button>
          {% else %}
          <button type="submit" name="like" class="btn btn-primary">Like</button>
          {% endif %}
      </form>
      {% else %}
      <p>Please log in to like this report.</p>
      {% endif %}
  </div>

  <span class="badge {% if report.status == 'Review-Pending' %} bg-warning {% elif report.status == 'Review-In-Progress' %} bg-info {% else %} bg-success {% endif %} float-end">
    {{ report.status }}
  </span>
  <p><strong>Reported by:</strong> {{ reporter_name }}</p>
  <p><strong>Reporter's email:</strong> {{ report.reporter_email }}</p>
  <p><strong>Company/Business Being Reported:</strong> {{ report.company_name }}</p>
  <p><strong>Reason:</strong> {{ report.reason }}</p>
  <p><strong>Category:</strong> {{ report.category }}</p>
  <p><strong>Report Date:</strong> {{ report.report_date }}</p>
  <h3>Files</h3>
  <ul class="list-group my-3">
    {% for s3_key, presigned_url, file_type in presigned_urls %}
    <li class="list-group-item">
        <p><strong>File Name:</strong> {{ s3_key }}</p>
    {% if file_type == 'jpeg' %}
        <img src="{{ presigned_url }}" style="max-width: 100%; height: auto;">
      {% elif file_type == 'jpg' %}
        <img src="{{ presigned_url }}" style="max-width: 100%; height: auto;">
      {% elif file_type == 'txt' %}
        <embed class="txt" src= "{{ presigned_url }}" width="100%" height="1000px">
      {% elif file_type == 'pdf' %}
        <embed class="pdf" src= "{{ presigned_url }}" width="100%" height="1000px">
      {% else %}
        <a href="{{ presigned_url }}" target="_blank">{{ s3_key }}</a>
      {% endif %}
    </li>
    {% endfor %}
  </ul>
  {% if user.is_superuser  and not user.is_staff %}
    {% if report.status == 'Review-In-Progress' %}
      <form action="{% url 'app:mark_review_completed' report.id %}" method="POST">
        {% csrf_token %}
        <p><strong>Admin Notes:</strong></p>
        <textarea class="form-control" name="message" id="message" placeholder="Resulting action..."></textarea>
        <br></br> 
        <button type="submit" class="btn btn-info mx-auto d-block">Submit Report Review</button>
      </form>
    {% endif %}
  {% endif %}
  {% if report.status == "Review-Completed" %}
    <p class="admin-notes"><strong>Admin Notes:</strong> {{ report.admin_notes}}</p>
  {% endif %}

</div>
<style>p {
    word-wrap: break-word;
}
.admin-notes {
    word-wrap: break-word;
    background-color: #62aef0;
}
</style>

{% endblock %}

templates/report_list.html
{% extends 'base.html' %}
{% block content %}
{% load socialaccount %}
{% if user.is_authenticated %}
{% if user.is_superuser and not user.is_staff %}
<div class="container">
  <h2>Reports For Admin</h2>
  <ul class="list-group">
    {% for report in reports %}
    <li class="list-group-item">
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <strong>{{ report.company_name }}</strong>
        </div>
          <div>
            <span class="badge {% if report.status == 'Review-Pending' %} bg-warning {% elif report.status == 'Review-In-Progress' %} bg-info {% else %} bg-success {% endif %}">
              {{ report.status }}
            </span>
          </div>
      </div>
      <div>
        Reporter Email: {{ report.reporter_email }}
      </div>
      <div>
        Report Details:  
        <a href="{% url 'app:report_detail' report.report_uuid %}">{{ report.reason }}</a>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% else %}
<div class="container">
  <h2>My Reports</h2>
  <ul class="list-group">
    {% for report in reports %}
    <li class="list-group-item">
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <strong>{{ report.company_name }}</strong>
        </div>
          <div>
            <span class="badge {% if report.status == 'Review-Pending' %} bg-warning {% elif report.status == 'Review-In-Progress' %} bg-info {% else %} bg-success {% endif %}">
              {{ report.status }}
            </span>
          </div>
      </div>
      <div class="container">  
        <a href="{% url 'app:report_detail' report.report_uuid %}">
          <p>{{ report.reason }}</p>
        </a>
      </div>

      <form method="POST" action="{% url 'app:delete_report' report.report_uuid %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}
{% else %}
<p>
 You are not logged in. Please login to view reports.
<p>
 {% endif %}
<style>

.list-group-item {
    word-wrap: break-word;
}
</style>
{% endblock %}

templates/report_success.html
{% extends "base.html" %}
{% block content %}
    <div class="container mt-3">
        <div class="alert alert-success" role="alert">Your report has been successfully submitted!</div>
    </div>
{% endblock %}

templates/reportform.html
{% extends "base.html" %}
{% block content %}
{% if not user.is_authenticated %}
<div class="alert alert-warning" role="alert">
        You are currently submitting the report as Anonymous. Please Login to be able to track your report.
    </div>
{% endif %}
        <form action="{% url 'app:report' %}"
              method="post"
              enctype="multipart/form-data"
              id="reportForm">
            {% csrf_token %}
            <fieldset>
                    <h1>Report Submission</h1>
                <div class="mb-3">
                    <label for="company_name" class="form-label">Company Name</label>
                    <input type="text"
                           class="form-control"
                           name="company_name"
                           id="company_name"
                           placeholder="Company Name">
                    {% if form.company_name.errors %}
                    <div class="alert alert-danger" role="alert">
                    {{ form.company_name.errors }}
                    </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="reason" class="form-label">Reason for reporting</label>
                    <textarea class="form-control" name="reason" id="reason" placeholder="Reasoning"></textarea>
                    {% if form.reason.errors %}
                        <div class="alert alert-danger" role="alert">
                        {{ form.reason.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="category" class="form-label">Category</label>
                    <select class="form-control" name="category" id="category">
                        <option value="Food">Food</option>
                        <option value="Retail">Retail</option>
                        <option value="Jobs">Jobs</option>
                        <option value="Services">Services</option>
                        <option value="Medical">Medical</option>
                        <option value="Other">Other</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="file" class="form-label">Upload files</label>
                    <input type="file"
                           class="form-control"
                           name="files"
                           id="file"
                           accept=".txt,.pdf,.jpg,.jpeg"
                           multiple>
                    <div class="small text-muted mt-2">
                        Please upload any files that support your claim. You may upload multiple files at once. (pdf, jpg, jpeg, txt)
                    </div>
                </div>
                <div id="loadingSpinner" class="text-center" style="display: none;">
                    <div class="spinner-border" role="status">
                    </div>
                </div>
                <input type="submit" value="Report" class="btn btn-danger">
        </form>



        <script>
        document.getElementById('reportForm').addEventListener('submit', function() {
            document.getElementById('loadingSpinner').style.display = 'block';
            this.querySelector('[type="submit"]').disabled = true;
        });
        </script>
    {% endblock %}

templates/signup.html
{% extends "base.html" %}

{% load crispy_forms_tags %}  

{% block content %}
<div class="container">
    <h1 class="mb-3">Sign up</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }} 
        <button type="submit" class="btn btn-primary mb-3">Sign up</button>  
    </form>
</div>
{% endblock %}